<x-app-layout><x-slot name="header"><h1 class="page-title">Mi perfil</h1><p class="page-subtitle">Actualice su información personal y credenciales.</p></x-slot>
@if(session('status')==='password-updated')<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Contraseña actualizada correctamente.</div>@endif
<div class="grid gap-6 xl:grid-cols-2"><section class="card-panel p-6 sm:p-8"><div class="mb-6"><h2 class="text-lg font-bold text-[#0b1f3a]">Información de perfil</h2><p class="mt-1 text-sm text-slate-500">Rol actual: {{ $user->rol?->nombre }}</p></div><form method="POST" action="{{ route('profile.update') }}" class="space-y-5" novalidate>@csrf @method('PATCH')
<div class="grid gap-5 sm:grid-cols-2"><div><label class="label-form" for="nombres">Nombres</label><input class="input-form @error('nombres') input-error @enderror" id="nombres" name="nombres" value="{{ old('nombres',$user->nombres) }}" required>@error('nombres')<p class="error-text">{{ $message }}</p>@enderror</div><div><label class="label-form" for="apellidos">Apellidos</label><input class="input-form @error('apellidos') input-error @enderror" id="apellidos" name="apellidos" value="{{ old('apellidos',$user->apellidos) }}" required>@error('apellidos')<p class="error-text">{{ $message }}</p>@enderror</div></div>
<div><label class="label-form" for="telefono">Teléfono</label><input class="input-form @error('telefono') input-error @enderror" id="telefono" name="telefono" value="{{ old('telefono',substr($user->telefono,0,4).'-'.substr($user->telefono,4)) }}" required>@error('telefono')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label class="label-form" for="email">Correo electrónico</label><input class="input-form @error('email') input-error @enderror" id="email" name="email" type="email" value="{{ old('email',$user->email) }}" required>@error('email')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label class="label-form" for="username">Nombre de usuario</label><input class="input-form @error('username') input-error @enderror" id="username" name="username" value="{{ old('username',$user->username) }}" required>@error('username')<p class="error-text">{{ $message }}</p>@enderror</div><div class="flex justify-end"><button class="btn-primary-101">Guardar perfil</button></div></form></section>
<section class="card-panel p-6 sm:p-8"><div class="mb-6"><h2 class="text-lg font-bold text-[#0b1f3a]">Cambiar contraseña</h2><p class="mt-1 text-sm text-slate-500">Utilice una contraseña que no emplee en otros servicios.</p></div><form method="POST" action="{{ route('password.update') }}" class="space-y-5">@csrf @method('PUT')
<div><label class="label-form" for="current_password">Contraseña actual</label><input class="input-form" id="current_password" name="current_password" type="password">@foreach($errors->updatePassword->get('current_password') as $message)<p class="error-text">{{ $message }}</p>@endforeach</div>
<div><label class="label-form" for="new_password">Nueva contraseña</label><input class="input-form" id="new_password" name="password" type="password">@foreach($errors->updatePassword->get('password') as $message)<p class="error-text">{{ $message }}</p>@endforeach</div>
<div><label class="label-form" for="password_confirmation">Confirmar nueva contraseña</label><input class="input-form" id="password_confirmation" name="password_confirmation" type="password"></div><div class="flex justify-end"><button class="btn-primary-101">Actualizar contraseña</button></div></form></section></div></x-app-layout>
