<x-app-layout>
<x-slot name="header"><h1 class="page-title">{{ $producto->exists ? 'Editar producto' : 'Agregar producto' }}</h1><p class="page-subtitle">Los costos internos solo son visibles para el Administrador.</p></x-slot>
<div class="card-panel max-w-4xl p-6">
@if($errors->any())<div role="alert" class="mb-5 rounded-xl bg-red-50 p-4 text-red-700">Revise los campos indicados. La información ingresada se conserva.</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $producto->exists ? route('productos.update',$producto) : route('productos.store') }}">
@csrf @if($producto->exists) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2">
@foreach(['codigo'=>['Código',40],'nombre'=>['Nombre del producto',150],'modelo'=>['Modelo / referencia',80]] as $field=>$meta)
<div><label class="label-form" for="{{ $field }}">{{ $meta[0] }}</label><input class="input-form @error($field) input-error @enderror" id="{{ $field }}" name="{{ $field }}" maxlength="{{ $meta[1] }}" value="{{ old($field,$producto->$field) }}" @required(in_array($field,['codigo','nombre'])) aria-describedby="error-{{ $field }}">@error($field)<p id="error-{{ $field }}" class="error-text">{{ $message }}</p>@enderror</div>
@endforeach
<div x-data="{ busqueda: '' }"><label class="label-form" for="buscar_marca">Buscar marca</label><input class="input-form mb-2" id="buscar_marca" type="search" x-model="busqueda" placeholder="Escriba para filtrar las marcas"><label class="label-form" for="id_marca">Seleccione una marca</label><select class="input-form" id="id_marca" name="id_marca" required><option value="">Seleccione una marca registrada</option>@foreach($marcas as $marca)<option value="{{ $marca->id_marca }}" x-show="$el.textContent.toLowerCase().includes(busqueda.toLowerCase())" @selected(old('id_marca',$producto->id_marca)==$marca->id_marca)>{{ $marca->nombre }}</option>@endforeach</select>@error('id_marca')<p class="error-text">{{ $message }}</p>@enderror<a class="text-sm text-blue-700" href="{{ route('marcas.index') }}">Administrar marcas</a></div><div><label class="label-form" for="id_categoria">Categoría</label><select class="input-form" id="id_categoria" name="id_categoria" required><option value="">Seleccione una categoría</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id_categoria }}" @selected(old('id_categoria',$producto->id_categoria)==$categoria->id_categoria)>{{ $categoria->nombre }}</option>@endforeach</select>@error('id_categoria')<p class="error-text">{{ $message }}</p>@enderror<a class="text-sm text-blue-700" href="{{ route('categorias.create') }}">Agregar categoría</a></div>
<div><label class="label-form" for="stock">Existencias</label><input class="input-form" id="stock" name="stock" type="number" min="0" max="1000000" step="1" required value="{{ old('stock',$producto->stock) }}">@error('stock')<p class="error-text">{{ $message }}</p>@enderror</div>
<div class="sm:col-span-2"><label class="label-form" for="descripcion">Descripción / especificaciones</label><textarea class="input-form" id="descripcion" name="descripcion" minlength="5" maxlength="3000" rows="4" required>{{ old('descripcion',$producto->descripcion) }}</textarea>@error('descripcion')<p class="error-text">{{ $message }}</p>@enderror</div>
@foreach(['precio_ingreso'=>'Precio de ingreso / compra','valor_real'=>'Valor real / costo total','valor_final'=>'Precio final de venta'] as $field=>$label)
<div><label class="label-form" for="{{ $field }}">{{ $label }} (USD)</label><input class="input-form" type="number" min="0" max="9999999999.99" step="0.01" id="{{ $field }}" name="{{ $field }}" required value="{{ old($field,$producto->$field) }}">@error($field)<p class="error-text">{{ $message }}</p>@enderror</div>
@endforeach
<div><label class="label-form" for="imagen">Fotografía</label><input class="input-form p-2" type="file" id="imagen" name="imagen" accept="image/jpeg,image/png,image/webp"><p class="mt-1 text-xs text-slate-500">JPG, PNG o WebP. Máximo 2 MB y 5000 × 5000 píxeles. Al editar, dejar vacío conserva la foto.</p>@error('imagen')<p class="error-text">{{ $message }}</p>@enderror</div>
<div class="sm:col-span-2"><input type="hidden" name="publicado" value="0"><label class="flex items-center gap-2"><input name="publicado" type="checkbox" value="1" @checked(old('publicado',$producto->publicado))>Mostrar en el catálogo público</label><p class="mt-2 text-xs text-slate-500">El público verá el precio final. Los costos de ingreso y real son internos.</p>@error('publicado')<p class="error-text">{{ $message }}</p>@enderror</div>
</div><div class="mt-7 flex justify-end gap-3"><a href="{{ route('productos.index') }}" class="btn-secondary-101">Cancelar</a><button class="btn-primary-101" type="submit">Guardar producto</button></div>
</form></div></x-app-layout>
