<div class="grid gap-5 sm:grid-cols-2">
<div><label for="nombres" class="label-form">Nombres <span class="text-red-600">*</span></label><input id="nombres" name="nombres" type="text" maxlength="100" required value="{{ old('nombres',$usuario->nombres ?? '') }}" class="input-form @error('nombres') input-error @enderror" placeholder="Ej. Carlos David">@error('nombres')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="apellidos" class="label-form">Apellidos <span class="text-red-600">*</span></label><input id="apellidos" name="apellidos" type="text" maxlength="100" required value="{{ old('apellidos',$usuario->apellidos ?? '') }}" class="input-form @error('apellidos') input-error @enderror" placeholder="Ej. Alfaro Ruiz">@error('apellidos')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="telefono" class="label-form">Teléfono <span class="text-red-600">*</span></label><input id="telefono" name="telefono" type="text" inputmode="numeric" maxlength="9" required value="{{ old('telefono',isset($usuario)?substr($usuario->telefono,0,4).'-'.substr($usuario->telefono,4):'') }}" class="input-form @error('telefono') input-error @enderror" placeholder="7000-0000"><p class="mt-1.5 text-xs text-slate-400">Número nacional de El Salvador.</p>@error('telefono')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="email" class="label-form">Correo electrónico <span class="text-red-600">*</span></label><input id="email" name="email" type="email" maxlength="150" required value="{{ old('email',$usuario->email ?? '') }}" class="input-form @error('email') input-error @enderror" placeholder="usuario@correo.com">@error('email')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="username" class="label-form">Nombre de usuario <span class="text-red-600">*</span></label><input id="username" name="username" type="text" maxlength="50" required value="{{ old('username',$usuario->username ?? '') }}" class="input-form @error('username') input-error @enderror" placeholder="carlos.alfaro"><p class="mt-1.5 text-xs text-slate-400">Sin espacios. Puede usar punto, guion o guion bajo.</p>@error('username')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="id_rol" class="label-form">Rol <span class="text-red-600">*</span></label><select id="id_rol" name="id_rol" required class="input-form @error('id_rol') input-error @enderror" @if(isset($usuario)&&auth()->id()===$usuario->id_usuario) disabled @endif><option value="">Seleccione</option>@foreach($roles as $rol)<option value="{{ $rol->id_rol }}" @selected((string)old('id_rol',$usuario->id_rol ?? '')===(string)$rol->id_rol)>{{ $rol->nombre }}</option>@endforeach</select>@if(isset($usuario)&&auth()->id()===$usuario->id_usuario)<input type="hidden" name="id_rol" value="{{ $usuario->id_rol }}"><p class="mt-1.5 text-xs text-slate-400">Por seguridad, no puede cambiar su propio rol desde esta pantalla.</p>@endif @error('id_rol')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="password" class="label-form">Contraseña @if(!isset($usuario))<span class="text-red-600">*</span>@endif</label><input id="password" name="password" type="password" autocomplete="new-password" @if(!isset($usuario)) required @endif class="input-form @error('password') input-error @enderror" placeholder="{{ isset($usuario)?'Dejar en blanco para conservar':'Mínimo 8 caracteres' }}"><p class="mt-1.5 text-xs text-slate-400">Debe incluir mayúsculas, minúsculas y números.</p>@error('password')<p class="error-text">{{ $message }}</p>@enderror</div>
<div><label for="password_confirmation" class="label-form">Confirmar contraseña @if(!isset($usuario))<span class="text-red-600">*</span>@endif</label><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" @if(!isset($usuario)) required @endif class="input-form" placeholder="Repita la contraseña"></div>
</div>
